config_interface -m_axi_auto_max_ports=true
config_interface -m_axi_auto_id_channel=true
config_interface -m_axi_flush_mode
config_interface -m_axi_latency 0
config_storage fifo -impl lutram
config_dataflow -default_channel fifo
config_dataflow -disable_fifo_sizing_opt